// 模拟用户数据
export const mockUsers = [
  {
    id: "admin1",
    username: "admin",
    password: "admin123",
    name: "系统管理员",
    role: "administrator",
    avatar: "/letter-a-abstract.png",
    email: "admin@example.com",
    phone: "13800000000",
    department: "大数据211",
    firstLogin: false,
  },
  {
    id: "manager1",
    username: "manager",
    password: "manager123",
    name: "张项目",
    role: "manager",
    avatar: "/abstract-geometric-z.png",
    email: "manager@example.com",
    phone: "13900000000",
    department: "大数据211",
    firstLogin: false,
  },
  {
    id: "volunteer1",
    username: "volunteer",
    password: "volunteer123",
    name: "李志愿",
    role: "volunteer",
    avatar: "/Abstract Letter L.png",
    email: "volunteer@example.com",
    phone: "13700000000",
    department: "计算机学院",
    creditScore: 3,
    serviceHours: 24,
    firstLogin: true,
    studentId: "2022010101",
    gender: "男",
    class: "计算机2201班",
    grade: "2022级",
  },
  {
    id: "volunteer2",
    username: "volunteer2",
    password: "volunteer123",
    name: "王小明",
    role: "volunteer",
    avatar: "/abstract-letter-w.png",
    email: "volunteer2@example.com",
    phone: "13600000000",
    department: "电子工程学院",
    creditScore: 3,
    serviceHours: 18,
    firstLogin: false,
    studentId: "2022020202",
    gender: "男",
    class: "电子2202班",
    grade: "2022级",
  },
  {
    id: "volunteer3",
    username: "volunteer3",
    password: "volunteer123",
    name: "赵小红",
    role: "volunteer",
    avatar: "/abstract-geometric-z.png",
    email: "volunteer3@example.com",
    phone: "13500000000",
    department: "计算机学院",
    creditScore: 0, // 黑名单用户
    serviceHours: 5,
    firstLogin: false,
    studentId: "2023010303",
    gender: "女",
    class: "计算机2301班",
    grade: "2023级",
  },
  {
    id: "volunteer4",
    username: "volunteer4",
    password: "volunteer123",
    name: "陈明月",
    role: "volunteer",
    avatar: "/placeholder.svg",
    email: "volunteer4@example.com",
    phone: "13400000000",
    department: "外国语学院",
    creditScore: 3,
    serviceHours: 15,
    firstLogin: false,
    studentId: "2021030404",
    gender: "女",
    class: "英语2101班",
    grade: "2021级",
  },
  {
    id: "volunteer5",
    username: "volunteer5",
    password: "volunteer123",
    name: "张阳光",
    role: "volunteer",
    avatar: "/placeholder.svg",
    email: "volunteer5@example.com",
    phone: "13300000000",
    department: "机械工程学院",
    creditScore: 3,
    serviceHours: 12,
    firstLogin: false,
    studentId: "2022040505",
    gender: "男",
    class: "机械2203班",
    grade: "2022级",
  },
]

// 模拟活动数据
export const mockActivities = [
  {
    id: "act1",
    title: "校园环保行动",
    description: "组织校园垃圾分类和回收活动，提高环保意识",
    location: "校园主广场",
    startTime: "2025-05-01T09:00:00",
    endTime: "2025-05-01T12:00:00",
    registrationDeadline: "2025-04-29T18:00:00",
    minParticipants: 5,
    maxParticipants: 20,
    currentParticipants: 3,
    serviceHours: 3,
    type: "环境保护",
    status: "approved", // pending, approved, rejected, canceled, completed
    managerId: "manager1",
    participants: ["volunteer1", "volunteer2"],
    createdAt: "2025-04-20T10:00:00",
    materials: null, // 活动证明材料
    isHot: true,
  },
  {
    id: "act2",
    title: "敬老院志愿服务",
    description: "前往市敬老院开展志愿服务，陪伴老人聊天、表演节目",
    location: "市第一敬老院",
    startTime: "2025-05-05T14:00:00",
    endTime: "2025-05-05T17:00:00",
    registrationDeadline: "2025-05-03T18:00:00",
    minParticipants: 8,
    maxParticipants: 15,
    currentParticipants: 10,
    serviceHours: 4,
    type: "关怀老人",
    status: "approved",
    managerId: "manager1",
    participants: ["volunteer1"],
    createdAt: "2025-04-22T14:30:00",
    materials: null,
    isHot: false,
  },
  {
    id: "act3",
    title: "图书馆整理志愿活动",
    description: "协助图书馆整理图书、维护阅览室秩序",
    location: "校图书馆",
    startTime: "2025-04-28T13:00:00",
    endTime: "2025-04-28T17:00:00",
    registrationDeadline: "2025-04-26T18:00:00",
    minParticipants: 3,
    maxParticipants: 10,
    currentParticipants: 2,
    serviceHours: 4,
    type: "校园活动",
    status: "approved",
    managerId: "manager1",
    participants: ["volunteer2"],
    createdAt: "2025-04-21T09:15:00",
    materials: null,
    isHot: true,
  },
  {
    id: "act4",
    title: "校园科技展志愿者",
    description: "在校园科技展担任讲解员和秩序维护",
    location: "科技楼展厅",
    startTime: "2025-05-10T08:30:00",
    endTime: "2025-05-10T16:30:00",
    registrationDeadline: "2025-05-08T18:00:00",
    minParticipants: 10,
    maxParticipants: 30,
    currentParticipants: 8,
    serviceHours: 8,
    type: "校园活动",
    status: "pending",
    managerId: "manager1",
    participants: [],
    createdAt: "2025-04-25T11:20:00",
    materials: null,
    isHot: false,
  },
  {
    id: "act5",
    title: "社区疫情防控宣传",
    description: "���往社区开展疫情防控知识宣传",
    location: "阳光社区",
    startTime: "2025-05-15T09:00:00",
    endTime: "2025-05-15T11:30:00",
    registrationDeadline: "2025-05-13T18:00:00",
    minParticipants: 6,
    maxParticipants: 12,
    currentParticipants: 0,
    serviceHours: 2.5,
    type: "健康",
    status: "approved",
    managerId: "manager1",
    participants: [],
    createdAt: "2025-04-26T16:45:00",
    materials: null,
    isHot: false,
  },
  {
    id: "act6",
    title: "养老院志愿服务",
    description: "前往阳光养老院进行志愿服务",
    location: "阳光养老院",
    startTime: "2025-01-10T08:30:00",
    endTime: "2025-01-10T16:30:00",
    registrationDeadline: "2025-05-08T18:00:00",
    minParticipants: 10,
    maxParticipants: 30,
    currentParticipants: 8,
    serviceHours: 8,
    type: "关怀老人",
    status: "pending",
    managerId: "manager1",
    participants: [],
    createdAt: "2025-04-25T11:20:00",
    materials: null,
    isHot: false,
  },
]

// 模拟公告数据
export const mockAnnouncements = [
  {
    id: "ann1",
    title: "志愿者管理系统正式上线",
    content: "我校志愿者管理系统已正式上线，请各位志愿者及时注册并完善个人信息。",
    createdBy: "admin1",
    createdAt: "2025-04-15T10:00:00",
    important: true,
  },
  {
    id: "ann2",
    title: "五月志愿服务月活动预告",
    content: "五月是我校志愿服务月，将有多项志愿活动开展，欢迎大家积极报名参与。",
    createdBy: "admin1",
    createdAt: "2025-04-20T14:30:00",
    important: false,
  },
  {
    id: "ann3",
    title: "关于志愿者信誉分制度的说明",
    content:
      "为了更好地管理志愿服务，我校实行志愿者信誉分制度。信誉分低于0的志愿者将被列入黑名单，一周内不能报名参加志愿活动。",
    createdBy: "admin1",
    createdAt: "2025-04-22T09:15:00",
    important: true,
  },
  {
    id: "4",
    title: "负责人培训通知",
    content: "所有活动负责人需参加5月5日下午2点在行政楼302会议室举行的培训会议，请准时参加。",
    publishDate: "2025-04-25",
    target: "manager",
    important: true,
    visible: true,
  },
  {
    id: "5",
    title: "系统维护通知",
    content: "系统将于5月1日凌晨2点至4点进行维护升级，期间系统将暂停服务，请各位用户提前做好准备。",
    publishDate: "2025-04-28",
    target: "all",
    important: false,
    visible: false,
  },
  {
    id: "6",
    title: "系统维护通知",
    content: "校园志愿服务管理系统将于2025年4月28日18：00进行维护，维护时间为10小时，预计与2025年",
    publishDate: "2025-04-25",
    target: "manager",
    important: true,
    visible: true,
  },
  {
    id: "7",
    title: "暑期志愿服务招募",
    content: "暑期社区服务项目现开放报名，5月10日前登录系统选择心仪项目，志愿服务时长可兑换学分。",
    publishDate: "2025-04-30",
    target: "volunteer",
    important: true,
    visible: true,
  },
  {
    id: "8",
    title: "服务时长统计通知",
    content: "2025年第一季度志愿服务时长已统计完成，请及时查看个人中心确认，如有异议请在5月15日前反馈。",
    publishDate: "2025-04-18",
    target: "all",
    important: false,
    visible: true,
  },
  {
    id: "9",
    title: "优秀志愿者表彰",
    content: "2024年度十佳志愿者评选结果已公布，请至行政楼大厅公示栏查看，颁奖仪式将于5月20日举行。",
    publishDate: "2025-05-05",
    target: "volunteer",
    important: true,
    visible: true,
  },
  {
    id: "10",
    title: "清明节服务暂停通知",
    content: "4月4日-4月6日期间暂停所有志愿服务活动，已报名活动顺延至节后，请相互转告。",
    publishDate: "2025-03-28",
    target: "all",
    important: false,
    visible: false,
  },
  {
    id: "11",
    title: "活动安全须知",
    content: "即日起所有户外活动需签署《安全责任书》，请负责人提前在活动管理页面下载模板。",
    publishDate: "2025-05-02",
    target: "manager",
    important: true,
    visible: true,
  },
  {
    id: "12",
    title: "系统反馈收集",
    content: "为优化服务体验，现征集系统改进建议，5月参与反馈的用户将获得10信誉分奖励。",
    publishDate: "2025-04-22",
    target: "all",
    important: false,
    visible: true,
  },
  {
    id: "13",
    title: "新功能上线公告",
    content: "【活动收藏夹】功能已上线，志愿者现在可以收藏心仪活动并设置开抢提醒，详见帮助中心。",
    publishDate: "2025-05-08",
    target: "volunteer",
    important: true,
    visible: true,
  },
  {
    id: "14",
    title: "证明材料补交提醒",
    content: "以下活动负责人请注意：4月15日前组织的活动需在5月1日前补交现场照片，逾期将影响审核。",
    publishDate: "2025-04-29",
    target: "manager",
    important: true,
    visible: true,
  },
  {
    id: "15",
    title: "志愿服务证书发放",
    content: "2024年度累计服务满50小时的志愿者，请于每周三下午至大学生活动中心308室领取证书。",
    publishDate: "2025-04-12",
    target: "volunteer",
    important: false,
    visible: true,
  },
  {
    id: "16",
    title: "系统登录安全提醒",
    content: "检测到非常用设备登录提醒，请所有用户及时绑定手机验证，账户异常请联系0371-12345678。",
    publishDate: "2025-05-03",
    target: "all",
    important: true,
    visible: true,
  },
]

// 模拟聊天数据
export const mockChats = [
  {
    id: "chat-act1",
    type: "group",
    name: "校园环保行动活动群",
    participants: ["manager1", "volunteer1", "volunteer2"],
    createdAt: "2025-04-20T10:00:00",
    messages: [
      {
        id: "msg1",
        senderId: "manager1",
        content: "欢迎大家加入校园环保行动活动群！",
        timestamp: "2025-04-20T10:05:00",
      },
      {
        id: "msg2",
        senderId: "volunteer1",
        content: "请问活动当天需要带什么工具吗？",
        timestamp: "2025-04-20T10:10:00",
      },
      {
        id: "msg3",
        senderId: "manager1",
        content: "不需要带特殊工具，我们会提供垃圾分类袋和手套。请大家穿着舒适的衣服和鞋子即可。",
        timestamp: "2025-04-20T10:15:00",
      },
    ],
  },
  {
    id: "chat-act2",
    type: "group",
    name: "敬老院志愿服务活动群",
    participants: ["manager1", "volunteer1"],
    createdAt: "2025-04-22T14:30:00",
    messages: [
      {
        id: "msg4",
        senderId: "manager1",
        content: "欢迎加入敬老院志愿服务活动群！",
        timestamp: "2025-04-22T14:35:00",
      },
      {
        id: "msg5",
        senderId: "volunteer1",
        content: "我有一些才艺表演，可以在活动中表演吗？",
        timestamp: "2025-04-22T15:00:00",
      },
      {
        id: "msg6",
        senderId: "manager1",
        content: "当然可以！请提前告诉我你要表演的内容，我们好安排时间。",
        timestamp: "2025-04-22T15:05:00",
      },
    ],
  },
]

// 模拟任务数据
export const mockTasks = [
  {
    id: "task1",
    title: "审批校园科技展志愿者活动",
    description: "需要审核活动详情",
    assigneeId: "admin1",
    dueDate: "2025-04-27T18:00:00",
    completed: false,
    createdAt: "2025-04-25T11:30:00",
  },
  {
    id: "task2",
    title: "上传敬老院志愿服务活动证明",
    description: "需要审核活动照片和服务时长证明",
    assigneeId: "manager1",
    dueDate: "2025-05-06T18:00:00",
    completed: false,
    createdAt: "2025-04-22T14:40:00",
  },
]

// 模拟报表数据
export const mockReports = {
  activityRanking: [
    { name: "李志愿", hours: 24, rank: 1 },
    { name: "王小明", hours: 18, rank: 2 },
    { name: "赵小红", hours: 5, rank: 3 },
  ],
  departmentRanking: [
    { name: "计算机学院", hours: 29, rank: 1 },
    { name: "电子工程学院", hours: 18, rank: 2 },
    { name: "机械工程学院", hours: 12, rank: 3 },
  ],
  gradeRanking: [
    { name: "2022级", count: 45, rank: 1 },
    { name: "2023级", count: 38, rank: 2 },
    { name: "2021级", count: 30, rank: 3 },
  ],
  activityTypePopularity: [
    { type: "环保", count: 120, percentage: 30 },
    { type: "关爱", count: 100, percentage: 25 },
    { type: "教育", count: 80, percentage: 20 },
    { type: "科技", count: 60, percentage: 15 },
    { type: "健康", count: 40, percentage: 10 },
  ],
  monthlyTrend: [
    { month: "1月", hours: 120 },
    { month: "2月", hours: 150 },
    { month: "3月", hours: 180 },
    { month: "4月", hours: 200 },
    { month: "5月", hours: 0 },
  ],
}
